server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dnegi3000/PIMConfService/
          searchPaths: src/main/resources/config
          username: dnegi3000
          password: 
          